project:
  type: website

website:
  title: "Linear Algebra"
  page-navigation: true
  page-footer: Copyright 2024, Karthik Thiagarajan @ IIT Madras
  navbar:
    pinned: true
    left:
      - text: "Home"
        file: index.md
      - text: "Maths-2"
        file: maths-2.md
      - text: "MLF"
        file: mlf.md
      - text: "Notes"
        file: notes_global.md
      - text: "Problems"
        file: problems_global.md
      - text: "About"
        file: about.md      

  sidebar:
    - title: "Maths-2"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - maths-2.md
        - section: "Live Sessions"
          contents:
            - maths-2/live_sessions/sessions.md
        - section: "Notes"
          contents:
            - section: "Week-1"
              contents:
              - maths-2/notes/week-1/note_1.qmd
              - maths-2/notes/week-1/note_2.md              
        - section: "Problems"
          contents:
            - section: "Week-1"
              contents:
                - maths-2/problems/week-1/problem_1.md
                - maths-2/problems/week-1/problem_2.qmd
                - maths-2/problems/week-1/problem_3.md
                - maths-2/problems/week-1/problem_4.md
                - maths-2/problems/week-1/problem_5.md
                - maths-2/problems/week-1/problem_6.qmd
                - maths-2/problems/week-1/problem_7.qmd
                - maths-2/problems/week-1/problem_8.md
        - maths-2/presentations/presentations.md

    - title: "Machine Learning Foundations"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - mlf.md


format:
  html:
    theme: cosmo
    fontsize: 20px
    toc: true
    grid:
      sidebar-width: 200px
      margin-width: 300px
      body-width: 800px
