project:
  type: website

website:
  title: "Linear Algebra"
  page-navigation: true
  page-footer: Copyright 2024, Karthik Thiagarajan @ IIT Madras
  navbar:
    pinned: true
    left:
      - text: "Home"
        file: index.md
      - text: "Maths-2"
        file: maths-2.md
      - text: "MLF"
        file: mlf.md
      - text: "Notes"
        file: notes.md
      - text: "Problems"
        file: problems.md
      - text: "About"
        file: about.md      

  sidebar:
    - title: "Maths-2"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - maths-2.md
        - auto: maths-2/notes
        - auto: maths-2/problems
        - auto: maths-2/presentations

    - title: "Problems"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents: 
        - problems.md
        - auto: problems/LADR
        - auto: problems/unsorted

    - title: "Machine Learning Foundations"
      collapse-level: 1
      border: true
      foreground: "primary"
      contents:
        - mlf.md


format:
  html:
    theme: cosmo
    fontsize: 20px
    toc: true
    grid:
      sidebar-width: 200px
      margin-width: 200px
      body-width: 900px
